# R/pkgmaker_core.R

#' Inicializar estructura del paquete
#' @param pkg_name Nombre del paquete
#' @param basedir Directorio base (default: ".")
pkgmaker_create <- function(pkg_name, basedir = ".") {
  pkg_path <- basedir # Usar ruta relativa simple para la app
  
  dir.create(pkg_path, showWarnings = FALSE, recursive = TRUE)
  dir.create(file.path(pkg_path, "R"), showWarnings = FALSE)
  dir.create(file.path(pkg_path, "man"), showWarnings = FALSE)
  dir.create(file.path(pkg_path, "data"), showWarnings = FALSE)
  
  # Plantilla DESCRIPTION
  desc_template <- sprintf("Package: %s
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors: Who wrote it
Maintainer: The Maintainer <yourself@somewhere.net>
Description: More about what it does (maybe more than one line)
    Use four spaces of indentation when describing parameters
License: What license is it under?
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1", pkg_name)
  
  writeLines(desc_template, file.path(pkg_path, "DESCRIPTION"))
  writeLines(c("# Generated by roxygen2: do not edit by hand", 
             "exportPattern(\"^[[:alpha:]]+\")"), 
             file.path(pkg_path, "NAMESPACE"))
  
  message("✓ Estructura creada en: ", pkg_path)
  invisible(pkg_path)
}

#' Compilar e Instalar (equivalente a pkgmaker compile)
pkgmaker_compile <- function(pkg_path = ".") {
  owd <- setwd(pkg_path)
  on.exit(setwd(owd))
  
  # Documentar
  message("📝 Documentando...")
  if (!requireNamespace("roxygen2", quietly = TRUE)) install.packages("roxygen2")
  roxygen2::roxygenise()
  
  # Instalar
  message("🔨 Compilando e instalando...")
  if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
  devtools::install()
  
  message("✓ Compilación e instalación completadas.")
}

#' Ejecutar Checks (equivalente a pkgmaker check)
pkgmaker_check <- function(pkg_path = ".") {
  owd <- setwd(pkg_path)
  on.exit(setwd(owd))
  
  message("🧪 Ejecutando R CMD CHECK...")
  if (!requireNamespace("rcmdcheck", quietly = TRUE)) install.packages("rcmdcheck")
  
  # Usamos rcmdcheck para un output más limpio en terminal
  check_results <- rcmdcheck::rcmdcheck(args = c("--as-cran"), error_on = "warning")
  
  if (!is.null(check_results$errors) || !is.null(check_results$warnings)) {
    message("⚠️  Se encontraron errores o advertencias.")
  } else {
    message("✅ Check pasado sin problemas.")
  }
  
  invisible(check_results)
}
